### ISSUE TITLE
Non utf-8 characters in filename (e.g. à é è) are lost in extraction 

### ISSUE THREAD

**Issue by vchalmel** [dtrx-py/dtrx#18] opened 2021-11-23 17:40 UTC

**Comment by ChrisJefferson** [comment] 2021-11-23 22:09
Could you give an example file?

**Comment by vchalmel** [comment] 2021-11-24 10:51
Yes, How would you do so ?

**Comment by noahp** [comment] 2021-11-24 20:40
If you could upload an example archive, that would be most helpful! I tested with a simple ZIP archive, and was unable to reproduce the problem:

```bash
❯ touch financière.xlsx

❯ zip financière.xlsx.zip financière.xlsx
  adding: financière.xlsx (stored 0%)

❯ dtrx financière.xlsx.zip
dtrx: WARNING: extracting /tmp/yolo/financière.xlsx.zip to financière.xlsx.1

❯ ls -l
total 4
-rw-rw-r-- 1 noah noah   0 Nov 24 15:39 financière.xlsx
-rw-rw-r-- 1 noah noah   0 Nov 24 15:39 financière.xlsx.1
-rw-rw-r-- 1 noah noah 182 Nov 24 15:39 financière.xlsx.zip
```

**Comment by noahp** [comment] 2022-02-20 17:32
Let me know if you have an example archive that reproduces this problem!

**Comment by noahp** [comment] 2022-09-16 13:04
Closing for now, I'm unable to reproduce the problem :( feel free to reopen if you have more information!

**Closed by noahp** 2022-09-16 13:04 UTC
